### ISSUE TITLE
Upload of 1,5 GByte zip file results in uploaded file being only 1,1 GByte in size

### ISSUE THREAD

**Issue by andreas-venturini** [mischa78/boxroom#48]
I set up boxroom with dokku on DigitalOcean and uploaded several files for testing purposes. There was no problem w/ upload and subsequent download of files smaller than 1 GByte. However, one zip file (size 1,5 GByte) that was working fine before upload somehow resulted in the uploaded file only being 1,1 GByte in size (the archive was not usable after downloading) despite the upload being successful (100% complete). I tried uploading several times and the result was the same each time. 
Nginx was configured to accept files up to 6 GByte. 

Has anybody had any similar issues with files exceeding the 1 GByte threshold?

**Comment by mischa78** [comment]
Hm, not sure what is going wrong here. I'm using Paperclip to handle file uploads on the server side. I had a quick look, but I don't see any limits regarding file size there. Did you check the log files? Any clues there?

**Comment by andreas-venturini** [comment]
I checked the logs and there is nothing unusual. It appears that boxroom believes the file has been uploaded successfully.

**Comment by mischa78** [comment]
Are you using Unicorn? Does the Unicorn log have anything regarding this?

**Comment by andreas-venturini** [comment]
Actually, after a closer look I found the following log entries:

```
Oct 08 21:03:14 boxroom puma: Completed 500 Internal Server Error in 14969ms (ActiveRecord: 21.2ms)
Oct 08 21:03:14 boxroom puma: Errno::ENOSPC (No space left on device - write):
Oct 08 21:03:14 boxroom puma: app/controllers/files_controller.rb:22:in `create'
```

I need to investigate whether this has something to do with space restrictions inside the docker app container (possibly related to the temporary storage that boxroom uses). 

However, the user should probably be informed about the failed upload rather than showing 100% complete status and offering the file for download.

**Comment by andreas-venturini** [comment]
So after some more investigation it turns out that our Nginx proxy was the culprit. Specifically, Nginx buffers any data sent from upstream (boxroom) to client devices on disk to minimize load on the application in case clients are slow. The maximum size of the temporary storage is set in the  `proxy_max_temp_file_size` directive and defaults to 1024m (which is exactly the size where the http download was cut).

The solution is to either disable on disk buffering by setting `proxy_max_temp_file_size` to 0 (that's what we did in our case, however your mileage might vary so make sure to understand possible implications) or to increase it's size. 

@mischa78 If you like I can create a pull request and add a section to your README for all those users who use Nginx as http proxy in combination with boxroom.

**Comment by mischa78** [comment]
Yes, that would be appreciated. Thanks for your interest and contributions!!
